version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image:
      ander2003vz/app-python-flask
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:admin123@db:5432/sistema_matricula
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: sistema_matricula
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
